namespace ModeloRegistro.model
{
    public class Anexo16_e
    {
        public int id { get; set; }
        public string tirista { get; set; }
        public string transeuntes { get; set; }
        public string eventos { get; set; }
        public string invitados { get; set; }
        public string estudiantes_programas_becas { get; set; }
        public string artistas { get; set; }
        public string periodistas { get; set; }
        public string religiosos { get; set; }
        public string diplomaticas { get; set; }
        public string tecnicos { get; set; }
        public string deportistas { get; set; }
        public string negocios { get; set; }
        public string otras { get; set; }
        public string fecha_solicitud { get; set; }
        public string pasaporte { get; set; }
        public string lugar_expedicion { get; set; }
        public string fecha_expedicion { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string padre { get; set; }
        public string madre { get; set; }
        public string lugar_nacimiento_padres { get; set; }
        public string estatura { get; set; }
        public string estado_civil { get; set; }
        public string m { get; set; }
        public string f { get; set; }
        public string blue_green_claros { get; set; }
        public string black_negros { get; set; }
        public string pardos { get; set; }
        public string piel_blanca { get; set; }
        public string piel_negra { get; set; }
        public string piel_albina { get; set; }
        public string piel_amarilla { get; set; }
        public string pelo_canoso { get; set; }
        public string pelo_negro { get; set; }
        public string pelo_rubio { get; set; }
        public string pelo_castaño { get; set; }
        public string pelo_rojo { get; set; }
        public string pelo_otro { get; set; }
        public string pais { get; set; }
        public string provincia { get; set; }
        public string ciudad_municipio { get; set; }
        public string fecha_nacimiento { get; set; }
        public string direccion { get; set; }
        public string codigo_postal { get; set; }
        public string provincia_estado_region { get; set; }
        public string pais_residencia_actual { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string nombre_centro_trabajo_estudio { get; set; }
        public string profecion { get; set; }
        public string ocupacion { get; set; }
        public string direccion_centro { get; set; }
        public string codigo_postal_centro { get; set; }
        public string provincia_estado_region_centro { get; set; }
        public string pais_centro { get; set; }
        public string telefono_centro { get; set; }
        public string fax_centro { get; set; }
        public string email_centro { get; set; }
        public string direccion_estancia_cuba { get; set; }
        public string nombre_apellido_persona_a_vicitar_cuba { get; set; }
        public string motivo_viaje_cuba { get; set; }
        public string tiempo_estancia { get; set; }
        public string lugar_fecha_salida_cuba { get; set; }
        public string lugar_fecha_llegada_cuba { get; set; }
        public string proposito_viaje_cuba { get; set; }
    }
}